import type { Product } from '@/types/product.types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Gulabi Anarkali Kurta Set',
    brand: 'Rang by Fleur',
    slug: 'gulabi-anarkali-kurta-set',
    price: 1899,
    compareAtPrice: 2799,
    category: 'kurtas',
    emoji: '👘',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 312,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Gulabi Pink', hex: '#F2A3BC' },
      { name: 'Ivory White', hex: '#FEF9F6' },
      { name: 'Mint Green', hex: '#A8D8C8' },
    ],
    description: 'A timeless anarkali kurta in soft cotton with delicate floral embroidery at the yoke and hem. Paired with a matching palazzo and dupatta, this set is perfect for festivals, family gatherings, or casual days when you want to feel effortlessly beautiful.',
    details: [
      '100% soft cotton fabric',
      'Full-length anarkali silhouette',
      'Delicate thread embroidery at yoke',
      'Comes with matching palazzo & dupatta',
      'Machine washable — cold water, gentle cycle',
      'Free alterations within 15 days',
    ],
    images: [],
    inStock: true,
    stockCount: 45,
    tags: ['kurta', 'anarkali', 'festive', 'cotton', 'ethnic'],
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'Floral Wrap Midi Dress',
    brand: 'Bloom Studio',
    slug: 'floral-wrap-midi-dress',
    price: 1299,
    compareAtPrice: 1799,
    category: 'dresses',
    emoji: '👗',
    badge: 'new',
    rating: 4.7,
    reviewCount: 189,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Rose Garden', hex: '#E07896' },
      { name: 'Sky Blue', hex: '#87CEEB' },
      { name: 'Butter Yellow', hex: '#F5E09A' },
    ],
    description: 'A breezy wrap midi dress in lightweight chiffon with an all-over floral print. The adjustable tie waist flatters every figure, and the midi length makes it suitable for brunch, dates, or casual office wear.',
    details: [
      '100% crinkle chiffon',
      'Adjustable wrap tie waist',
      'Midi length — below knee',
      'Fully lined inner',
      'Hand wash recommended',
    ],
    images: [],
    inStock: true,
    stockCount: 78,
    tags: ['dress', 'floral', 'western', 'chiffon', 'casual'],
    createdAt: '2025-02-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Chanderi Silk Saree',
    brand: 'Zari & Co.',
    slug: 'chanderi-silk-saree',
    price: 3499,
    compareAtPrice: 4999,
    category: 'sarees',
    emoji: '🥻',
    badge: 'sale',
    rating: 4.9,
    reviewCount: 95,
    sizes: ['Free Size'],
    colors: [
      { name: 'Peach Blossom', hex: '#FFCBA4' },
      { name: 'Lavender Mist', hex: '#D8B4FE' },
      { name: 'Sage Green', hex: '#9DC88D' },
    ],
    description: 'A lightweight Chanderi silk saree with zari border weave. The sheer texture with golden zari motifs catches light beautifully. Comes with a matching unstitched blouse piece.',
    details: [
      'Pure Chanderi silk — 5.5 metres',
      'Handwoven zari border',
      'Matching unstitched blouse piece included',
      'Dry clean only',
      'Woven in Chanderi, Madhya Pradesh',
    ],
    images: [],
    inStock: true,
    stockCount: 28,
    tags: ['saree', 'chanderi', 'silk', 'zari', 'wedding', 'festive'],
    createdAt: '2024-12-15T00:00:00Z',
  },
  {
    id: '4',
    name: 'Breezy Linen Co-ord Set',
    brand: 'Bloom Studio',
    slug: 'breezy-linen-coord-set',
    price: 1599,
    category: 'tops',
    emoji: '👚',
    badge: 'new',
    rating: 4.6,
    reviewCount: 143,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Sand Dune', hex: '#E2C4B0' },
      { name: 'Soft Lilac', hex: '#D4B8E0' },
      { name: 'Pistachio', hex: '#B5CC8E' },
    ],
    description: 'A relaxed linen co-ord set with a cropped shirt and wide-leg trousers. Minimal yet effortlessly stylish — perfect for college, brunch, or a day out shopping.',
    details: [
      '55% linen, 45% cotton blend',
      'Cropped oversized shirt + wide-leg pants',
      'Button-down shirt with chest pocket',
      'Elastic waistband trousers',
      'Machine washable',
    ],
    images: [],
    inStock: true,
    stockCount: 92,
    tags: ['coord', 'linen', 'western', 'casual', 'college'],
    createdAt: '2025-02-14T00:00:00Z',
  },
  {
    id: '5',
    name: 'Embroidered Organza Dupatta',
    brand: 'Rang by Fleur',
    slug: 'embroidered-organza-dupatta',
    price: 649,
    category: 'accessories',
    emoji: '🧣',
    rating: 4.5,
    reviewCount: 267,
    sizes: ['Free Size'],
    colors: [
      { name: 'Blush Pink', hex: '#F9CCDA' },
      { name: 'Midnight Blue', hex: '#1E3A5F' },
      { name: 'Ivory', hex: '#FEF9F6' },
    ],
    description: 'A sheer organza dupatta with delicate mirror and thread embroidery all over. Light as air and strikingly beautiful — elevates any kurta or suit instantly.',
    details: [
      '100% pure organza',
      'Hand-embroidered mirror work',
      '2.5 metres length',
      'Dry clean recommended',
    ],
    images: [],
    inStock: true,
    stockCount: 134,
    tags: ['dupatta', 'organza', 'embroidery', 'accessories', 'ethnic'],
    createdAt: '2025-01-20T00:00:00Z',
  },
  {
    id: '6',
    name: 'Lehenga Choli — Bridal Edit',
    brand: 'Zari & Co.',
    slug: 'lehenga-choli-bridal-edit',
    price: 8999,
    compareAtPrice: 12999,
    category: 'sarees',
    emoji: '🥻',
    badge: 'bestseller',
    rating: 5.0,
    reviewCount: 61,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    colors: [
      { name: 'Rani Pink', hex: '#C4728A' },
      { name: 'Royal Red', hex: '#9B1B30' },
      { name: 'Marigold', hex: '#E8A530' },
    ],
    description: 'A showstopping bridal lehenga choli with heavy zardozi and sequin embroidery. The flared lehenga, fitted choli, and dupatta come as a complete set. Custom stitching available in 15 days.',
    details: [
      'Heavy embroidered net fabric',
      'Zardozi + sequin + thread work',
      'Fully flared lehenga — 4 metres flair',
      'Custom stitching available',
      'Includes lehenga, choli, and dupatta',
      'Dry clean only',
    ],
    images: [],
    inStock: true,
    stockCount: 15,
    tags: ['lehenga', 'bridal', 'wedding', 'festive', 'zardozi'],
    createdAt: '2024-11-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Palazzo Kurta Set — Printed',
    brand: 'Rang by Fleur',
    slug: 'palazzo-kurta-set-printed',
    price: 1199,
    category: 'kurtas',
    emoji: '👘',
    rating: 4.5,
    reviewCount: 224,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Terracotta', hex: '#E2725B' },
      { name: 'Cobalt Blue', hex: '#3B6FAF' },
      { name: 'Olive Grove', hex: '#707B4F' },
    ],
    description: 'A breezy block-printed kurta with matching palazzo trousers. Rayon fabric keeps you cool through long days. Great for daily wear, office, or casual outings.',
    details: [
      '100% rayon — lightweight & breathable',
      'Hand block-printed design',
      'Straight kurta with side slits',
      'Elastic waist palazzo',
      'Machine washable',
    ],
    images: [],
    inStock: true,
    stockCount: 117,
    tags: ['kurta', 'palazzo', 'printed', 'rayon', 'daily wear'],
    createdAt: '2025-01-08T00:00:00Z',
  },
  {
    id: '8',
    name: 'Pearl Drop Earrings',
    brand: 'Zari & Co.',
    slug: 'pearl-drop-earrings',
    price: 449,
    category: 'accessories',
    emoji: '💍',
    badge: 'new',
    rating: 4.7,
    reviewCount: 398,
    sizes: ['Free Size'],
    colors: [
      { name: 'Pearl White', hex: '#F8F4F0' },
      { name: 'Rose Gold', hex: '#E8B4A0' },
    ],
    description: 'Lightweight pearl drop earrings with a gold-tone base. Pairs beautifully with both ethnic and western outfits. Hypoallergenic and suitable for sensitive ears.',
    details: [
      'Artificial pearl with gold-tone base',
      'Hypoallergenic — safe for sensitive skin',
      'Hook earrings — easy to wear',
      'Length: 4.5 cm',
      'Gift box included',
    ],
    images: [],
    inStock: true,
    stockCount: 210,
    tags: ['earrings', 'pearl', 'jewellery', 'accessories', 'gift'],
    createdAt: '2025-02-18T00:00:00Z',
  },
  {
    id: '9',
    name: 'Ribbed Crop Top & Skirt Set',
    brand: 'Bloom Studio',
    slug: 'ribbed-crop-top-skirt-set',
    price: 999,
    category: 'tops',
    emoji: '👚',
    rating: 4.4,
    reviewCount: 176,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Mocha Brown', hex: '#9E7A62' },
      { name: 'Dusty Rose', hex: '#D4928A' },
      { name: 'Charcoal', hex: '#5A5A5A' },
    ],
    description: 'A ribbed knit two-piece set with a fitted crop top and a flared midi skirt. Easy to style up or down — perfect for college, cafes, or weekend outings.',
    details: [
      '95% cotton, 5% elastane ribbed knit',
      'Crop top with round neck',
      'Flared midi skirt with elastic waist',
      'Stretchable fabric — fits true to size',
      'Machine washable',
    ],
    images: [],
    inStock: true,
    stockCount: 88,
    tags: ['coord', 'ribbed', 'western', 'casual', 'co-ord set'],
    createdAt: '2025-01-25T00:00:00Z',
  },
  {
    id: '10',
    name: 'Bandhani Print Straight Kurta',
    brand: 'Rang by Fleur',
    slug: 'bandhani-print-straight-kurta',
    price: 899,
    category: 'kurtas',
    emoji: '👘',
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 445,
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: [
      { name: 'Indigo Blue', hex: '#3D56A6' },
      { name: 'Magenta Pink', hex: '#C0366A' },
      { name: 'Mustard', hex: '#D4A02A' },
    ],
    description: 'A straight-cut kurta in soft cotton with traditional Bandhani (tie-dye) print. One of our most-loved styles — looks stunning with churidar, leggings, or even jeans.',
    details: [
      '100% cotton — skin-friendly',
      'Traditional Bandhani tie-dye print',
      'Straight cut with V-neck',
      'Full button opening at neck',
      'Machine washable',
      'Size inclusive — XS to 3XL',
    ],
    images: [],
    inStock: true,
    stockCount: 230,
    tags: ['kurta', 'bandhani', 'cotton', 'ethnic', 'bestseller'],
    createdAt: '2024-10-01T00:00:00Z',
  },
  {
    id: '11',
    name: 'Satin Slip Midi Dress',
    brand: 'Bloom Studio',
    slug: 'satin-slip-midi-dress',
    price: 1499,
    compareAtPrice: 1999,
    category: 'dresses',
    emoji: '👗',
    badge: 'sale',
    rating: 4.6,
    reviewCount: 132,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Champagne', hex: '#F5DEB3' },
      { name: 'Blush Pink', hex: '#FFB6C1' },
      { name: 'Forest Green', hex: '#3A6B4A' },
    ],
    description: 'A silky satin slip dress with thin adjustable straps and a bias-cut finish that glides over the body. Wear alone for evenings or layer over a tee for a daytime aesthetic look.',
    details: [
      'Soft satin-finish polyester',
      'Adjustable spaghetti straps',
      'Bias-cut for a fluid drape',
      'Side slit at hem',
      'Hand wash or gentle machine wash',
    ],
    images: [],
    inStock: true,
    stockCount: 54,
    tags: ['dress', 'satin', 'slip dress', 'western', 'evening'],
    createdAt: '2025-01-30T00:00:00Z',
  },
  {
    id: '12',
    name: 'High-waist Flare Jeans',
    brand: 'Bloom Studio',
    slug: 'high-waist-flare-jeans',
    price: 1799,
    category: 'bottoms',
    emoji: '👖',
    badge: 'new',
    rating: 4.5,
    reviewCount: 203,
    sizes: ['26', '28', '30', '32', '34', '36'],
    colors: [
      { name: 'Classic Blue', hex: '#5B7FA6' },
      { name: 'Vintage Black', hex: '#2A2A2A' },
      { name: 'Light Wash', hex: '#B0C8E0' },
    ],
    description: 'High-waist flare jeans with a flattering fit through the hip and thigh that opens into a wide flare below the knee. A 90s style staple reborn for today.',
    details: [
      '98% cotton, 2% elastane denim',
      'High-rise waist — 11 inch rise',
      'Flare from knee downward',
      'Five-pocket style',
      'Machine washable',
    ],
    images: [],
    inStock: true,
    stockCount: 67,
    tags: ['jeans', 'flare', 'western', 'denim', 'bottoms'],
    createdAt: '2025-02-20T00:00:00Z',
  },
]